### ISSUE TITLE
Improvements for Better User Experience

### ISSUE THREAD

**Issue by Antoniaiaiaiaia** [Phala-Network/apps-ng#10]
1. Placeholder "Send to address" when clicking Send Transfer should be "Recipient address"
2. Phala logo which is at upper left might link to Phala official: http://phala.network/
3. A footer might be necessary for newcomers to get access to the resources he or she needs (a simple line of words would be cool): [Github](https://github.com/Phala-Network)   [Forum](https://forum.phala.network/)   [Telegram](https://t.me/phalanetwork)    [Discird](https://discord.gg/FUtZzYH)    [Twitter](https://twitter.com/PhalaNetwork)
4. It would be better for Intros of modules are aligned to the same line, and they could be replaced as "Visible Assets" / "Invisible Assets". Example: https://pasteboard.co/JlQnWaL.png

**Comment by h4x3rotab** [comment]
> 1. Placeholder "Send to address" when clicking Send Transfer should be "Recipient address"

This is from polkadotjs-ui. We don't want to fix.

**Comment by jasl** [comment]
1 won't change for now, it's from Polkadot.js SDK

**Comment by krhougs** [comment]
1. 
![image](https://user-images.githubusercontent.com/1382065/90114691-a7926700-dd85-11ea-98f0-e7174b941b5f.png)

**Comment by jasl** [comment]
1 won't change for now, it's from Polkadot.js SDK
2 will do
3 will do
4 won't change for now, and the link broken, you can paste PNG here directly

**Comment by Antoniaiaiaiaia** [comment]
![](https://imgur.com/vSMCQMU.png)
