### ISSUE TITLE
Change the color of "Issue Secret Token"

### ISSUE THREAD

**Issue by Antoniaiaiaiaia** [Phala-Network/apps-ng#9]
It would be better if the color of a button could be different with narrative information. For authentic consideration, you may set it as the same green color as the wallet above.

**Comment by h4x3rotab** [comment]
Let's change the border color to the primary color. The text color and the background color can be kept.

**Comment by Antoniaiaiaiaia** [comment]
cool

h4x3rotab <notifications@github.com> 于2020年8月11日周二 下午6:25写道：

**Comment by krhougs** [comment]
Improper priority.
![image](https://user-images.githubusercontent.com/1382065/90115515-cba27800-dd86-11ea-954a-4dd0779292dd.png)
